<a href="https://colab.research.google.com/github/vg11072001/natural-language-processing/blob/main/deep%20learning%20-%20RNN%2C%20LSTM%2C%20BERT%2C%20Transformer/Word_embedding_Techniques.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Word Embedding Techniques using Embedding Layer in Keras

In [1]:
### Libraries USed Tensorflow> 2.0  and keras

In [2]:
!pip install tensorflow-gpu

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 588.3 MB 21 kB/s 
     |████████████████████████████████| 1.7 MB 57.8 MB/s 
     |████████████████████████████████| 439 kB 76.0 MB/s 
     |████████████████████████████████| 6.0 MB 69.1 MB/s 
  Attempting uninstall: tensorflow-estimator
    Found existing installation: tensorflow-estimator 2.9.0
    Uninstalling tensorflow-estimator-2.9.0:
      Successfully uninstalled tensorflow-estimator-2.9.0
  Attempting uninstall: tensorboard
    Found existing installation: tensorboard 2.9.1
    Uninstalling tensorboard-2.9.1:
      Successfully uninstalled tensorboard-2.9.1
  Attempting uninstall: keras
    Found existing installation: keras 2.9.0
    Uninstalling keras-2.9.0:
      Successfully uninstalled keras-2.9.0
  Attempting uninstall: flatbuffers
    Found existing installation: flatbuffers 1.12
    Uninstalling flatbuffers-1.12:
      Successfully u

In [3]:
import tensorflow as tf
print(tf.__version__)

2.11.0


In [4]:
##tensorflow >2.0
from tensorflow.keras.preprocessing.text import one_hot

In [5]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good']

In [6]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [7]:
### Vocabulary size
voc_size=500

#### One Hot Representation

In [8]:
onehot_repr=[one_hot(words,voc_size)for words in sent] 
print(onehot_repr)

[[431, 288, 466, 173], [431, 288, 466, 52], [431, 97, 466, 37], [396, 54, 271, 75, 176], [396, 54, 271, 75, 323], [446, 431, 262, 466, 480], [79, 266, 406, 75]]


### Word Embedding Represntation

In [9]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [10]:
import numpy as np

In [11]:
## pre padding
sent_length=8
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length) #pre or post
print(embedded_docs)

[[  0   0   0   0 431 288 466 173]
 [  0   0   0   0 431 288 466  52]
 [  0   0   0   0 431  97 466  37]
 [  0   0   0 396  54 271  75 176]
 [  0   0   0 396  54 271  75 323]
 [  0   0   0 446 431 262 466 480]
 [  0   0   0   0  79 266 406  75]]


In [12]:
## 10 feature dimesnions
dim=10


In [13]:
model=Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length))
model.compile('adam','mse')

In [14]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             5000      
                                                                 
Total params: 5,000
Trainable params: 5,000
Non-trainable params: 0
_________________________________________________________________


In [15]:
##'the glass of milk',
embedded_docs[0]

array([  0,   0,   0,   0, 431, 288, 466, 173], dtype=int32)

In [16]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 69ms/step


array([[-0.00853352, -0.03817616, -0.03406896, -0.00016288,  0.03229756,
        -0.02082065,  0.01469362,  0.02971946, -0.04030919, -0.0255996 ],
       [-0.00853352, -0.03817616, -0.03406896, -0.00016288,  0.03229756,
        -0.02082065,  0.01469362,  0.02971946, -0.04030919, -0.0255996 ],
       [-0.00853352, -0.03817616, -0.03406896, -0.00016288,  0.03229756,
        -0.02082065,  0.01469362,  0.02971946, -0.04030919, -0.0255996 ],
       [-0.00853352, -0.03817616, -0.03406896, -0.00016288,  0.03229756,
        -0.02082065,  0.01469362,  0.02971946, -0.04030919, -0.0255996 ],
       [ 0.00816058,  0.01237323,  0.02056812,  0.00240614, -0.01367014,
        -0.02577491,  0.0128651 ,  0.04323825, -0.04324253, -0.04588889],
       [ 0.02852141,  0.00028582, -0.04847406,  0.03091565, -0.04063823,
        -0.00558642, -0.01298889, -0.02087606,  0.03976538, -0.04874906],
       [ 0.02872713, -0.00914172,  0.04347495, -0.03983753,  0.04799494,
         0.02843003,  0.00888339, -0.03077892

In [17]:
print(model.predict(embedded_docs))

1/1 [==============================] - 0s 36ms/step
[[[-0.00853352 -0.03817616 -0.03406896 -0.00016288  0.03229756
   -0.02082065  0.01469362  0.02971946 -0.04030919 -0.0255996 ]
  [-0.00853352 -0.03817616 -0.03406896 -0.00016288  0.03229756
   -0.02082065  0.01469362  0.02971946 -0.04030919 -0.0255996 ]
  [-0.00853352 -0.03817616 -0.03406896 -0.00016288  0.03229756
   -0.02082065  0.01469362  0.02971946 -0.04030919 -0.0255996 ]
  [-0.00853352 -0.03817616 -0.03406896 -0.00016288  0.03229756
   -0.02082065  0.01469362  0.02971946 -0.04030919 -0.0255996 ]
  [ 0.00816058  0.01237323  0.02056812  0.00240614 -0.01367014
   -0.02577491  0.0128651   0.04323825 -0.04324253 -0.04588889]
  [ 0.02852141  0.00028582 -0.04847406  0.03091565 -0.04063823
   -0.00558642 -0.01298889 -0.02087606  0.03976538 -0.04874906]
  [ 0.02872713 -0.00914172  0.04347495 -0.03983753  0.04799494
    0.02843003  0.00888339 -0.03077892 -0.02447654  0.00099509]
  [-0.00612438  0.01991886  0.03594052 -0.03995347  0.00599

In [18]:
embedded_docs[0]

array([  0,   0,   0,   0, 431, 288, 466, 173], dtype=int32)

In [19]:
print(model.predict(embedded_docs)[0])

1/1 [==============================] - 0s 19ms/step
[[-0.00853352 -0.03817616 -0.03406896 -0.00016288  0.03229756 -0.02082065
   0.01469362  0.02971946 -0.04030919 -0.0255996 ]
 [-0.00853352 -0.03817616 -0.03406896 -0.00016288  0.03229756 -0.02082065
   0.01469362  0.02971946 -0.04030919 -0.0255996 ]
 [-0.00853352 -0.03817616 -0.03406896 -0.00016288  0.03229756 -0.02082065
   0.01469362  0.02971946 -0.04030919 -0.0255996 ]
 [-0.00853352 -0.03817616 -0.03406896 -0.00016288  0.03229756 -0.02082065
   0.01469362  0.02971946 -0.04030919 -0.0255996 ]
 [ 0.00816058  0.01237323  0.02056812  0.00240614 -0.01367014 -0.02577491
   0.0128651   0.04323825 -0.04324253 -0.04588889]
 [ 0.02852141  0.00028582 -0.04847406  0.03091565 -0.04063823 -0.00558642
  -0.01298889 -0.02087606  0.03976538 -0.04874906]
 [ 0.02872713 -0.00914172  0.04347495 -0.03983753  0.04799494  0.02843003
   0.00888339 -0.03077892 -0.02447654  0.00099509]
 [-0.00612438  0.01991886  0.03594052 -0.03995347  0.00599873 -0.04806892